### PR TITLE
Fixes for uncrustify 0.72

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

Links to https://github.com/ament/uncrustify_vendor/pull/27 ; see that PR for more information and CI.

### CODE REVIEW

**Review by audrow — APPROVED** [review]

**Comment by clalancette** [comment]
@MichaelOrlov @emersonknapp @gbiggs @christophebedard This PR has to go in concurrently with all of the PRs listed in https://github.com/ament/uncrustify_vendor/pull/27 (if we merge it before or after, we are going to break CI).  As it stands, I don't have write access to this repository, so I can't actually do the merge here.  A couple of solutions come to mind:

1. Someone can give me (temporary) write access so I can do this merge
2. Someone can be ready to do the merge when I go ahead and merge the uncrustify_vendor PR and all of the siblings.

Either works for me, we just need to coordinate.  Thoughts?

**Review by christophebedard — APPROVED** [review]
Looks good to me. Local CI fails because it's not using https://github.com/ament/uncrustify_vendor/pull/27, so it's alright.

**Comment by christophebedard** [comment]
> Either works for me, we just need to coordinate. Thoughts?

I can merge it whenever you're ready.

**Comment by clalancette** [comment]
> I can merge it whenever you're ready.

All right, sounds good.  I'll start merging the rest of the PRs soon here, and ping back once the rest of them are in.

**Comment by clalancette** [comment]
@christophebedard OK, all of the rest of the PRs have been merged.  This one is ready to merge when you are ready.

**Comment by clalancette** [comment]
Thank you so much!

**Comment by clalancette** [comment]
@christophebedard If you get a chance, a new release of `keyboard_handler` into Rolling would be appreciated.  Until that gets done, all of the Rpr jobs to this repository are going to fail.

**Comment by christophebedard** [comment]
@clalancette I could tag a new release, but I don't have access to the release repo (https://github.com/ros2-gbp/keyboard_handler-release). @emersonknapp could probably do it at some point.

**Comment by emersonknapp** [comment]
Thanks for taking care of all this while I was on vacation - I'll cut a new release today.

**Comment by emersonknapp** [comment]
https://github.com/ros/rosdistro/pull/31533

**Pull request merged**
