### PR TITLE
Install includes to include/${PROJECT_NAME} and misc CMake fixes

### PR DESCRIPTION
**Pull request by sloretz**
Part of ros2/ros2#1150

This installs includes to `include/${PROJECT_NAME}` to mitigate include directory search order issues when overriding packages in desktop.

~Part of ament/ament_cmake#365~

~This removes `ament_export_libraries` and `ament_export_include_directories` as they're redundant with the exported CMake targets.~ **Edit: added back old-style CMake variables to minimize disruption**

### CODE REVIEW

**Comment by sloretz** [comment]
Uncrustify failure appears to be due to changes in c0014bf389a23d8de5af44d130dd505c7fa69a89 that satisfy Uncrustify 0.72, but don't satisfy 0.69. That will be fixed whenever uncrustify_vendor gets a new rolling release. Since the code in question isn't changed by this PR, CI LGTM

**Review by emersonknapp — APPROVED** [review]

**Comment by sloretz** [comment]
CI ([repos file](https://gist.githubusercontent.com/sloretz/8ffc50076bf045bd4364837d0705b4c8/raw/61ab626293403131d6b5abb861dd15867578b47f/ros2.repos) build: `--packages-above-and-dependencies keyboard_handler` test: `--packages-above keyboard_handler`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15991/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10660/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16314/)

**Comment by sloretz** [comment]
@emersonknapp would you be willing to merge this PR? I don't have write access to this repo

**Comment by christophebedard** [comment]
Everything seems to be in order so I'll just merge it!

**Pull request merged**
