### PR TITLE
Unified keyboard handler

### PR DESCRIPTION
**Pull request by MichaelOrlov**
Part of [#696](https://github.com/ros2/rosbag2/issues/696)

Keyboard handler handles key pressing via registered callbacks.

Moved keyboard handler from https://github.com/ros2/rosbag2/pull/735 to the `ros-tooling`
+ Added changes to the API to be able specify key modifiers as a separate parameter in callbacks.

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@emersonknapp Could you please review this PR?
I also would like to ask you to help me with setting up github configuration for `keyboard_handler` repo to be able to run some linters and basic tests when pushing new commits as well as require approval before merge.

**Comment by emersonknapp** [comment]
Yes - I'll help setting up the GH configuration. I'll get some PRs up for that today.

**Review by emersonknapp — APPROVED** [review]
I believe I mostly reviewed in the prior PR - let's move forward and can always refactor if needed

**Comment by MichaelOrlov** [comment]
Running CI
Gist: 
https://gist.githubusercontent.com/MichaelOrlov/f12c97b839c0e0d48fcebebcf78c5418/raw/240eb2447f12972e84f367e0d3e18071b526d789/ros2.repos
BUILD args: --packages-up-to keyboard_handler
TEST args: --packages-select keyboard_handler
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/8576/
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14759/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9509/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12424/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14907/)

**Comment by MichaelOrlov** [comment]
Rerunning CI after fixing compiler warnings
Gist: 
https://gist.githubusercontent.com/MichaelOrlov/f12c97b839c0e0d48fcebebcf78c5418/raw/240eb2447f12972e84f367e0d3e18071b526d789/ros2.repos
BUILD args: --packages-up-to keyboard_handler
TEST args: --packages-select keyboard_handler
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/8577/
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14760/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9510/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12425/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14908/)

**Pull request merged**
